# Generated by Django 4.2.5 on 2023-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url',
            field=models.URLField(default='Student', verbose_name='Url'),
            preserve_default=False,
        ),
    ]
